### ISSUE TITLE
Keeping in sync with Plover

### ISSUE THREAD

**Issue by didoesdigital** [didoesdigital/steno-dictionaries#1]
Plover removes bad strokes and adds useful suggestions irregularly from comments in this issue: [Dictionary Suggestions #400](https://github.com/openstenoproject/plover/issues/400).

Keeping `dict.json` in sync with Plover's `main.json` may help newcomers learn from [Typey Type for Stenographers](https://didoesdigital.com/typey-type/) without Plover's misstrokes as well as keep up with Plover's main community dictionary. If they get far out of sync, it will be harder for beginners to understand what strokes to use, why certain translations exist, and have a harder time choosing between them.

The current practice for Plover developers is to delete comments on the suggestions thread as they get merged to the dictionary. To preserve the history of those comments and reasoning for dictionary changes, we might continuously commit changes, referencing the original comments.

**Comment by didoesdigital** [comment]
To avoid getting ahead of releases of the Plover dictionary with Plover app releases, we could hold back the changes here on a separate branch. When a Plover version is released with a dictionary update, we can merge the branch back into master. Meanwhile, anyone that wants the bleeding edge dictionary can use the branch dictionary.

**Comment by didoesdigital** [comment]
No releases of the Plover app have been made. The open PR has conflicts almost beyond repair. This approach needs rethinking.

**Comment by paulfioravanti** [comment]
I'm of the opinion that this issue can be credibly closed as a `wontfix`.

I think Mirabai's steno dictionary at the time, that became `main.json` for Plover the theory, should really be considered a "starter" dictionary that every Plover user can take, build on, change, or ignore. Mirabai has said herself in the Plover Discord that her dictionary has, unsurprisingly, evolved significantly since it was first gifted to the Plover repo. Understandably, there does not seem to be the intention to merge those changes, or any other future changes, into `main.json`, and take up that continued maintenance burden.

I do not think `main.json` can really be classified as a "community" dictionary either, both due to it not being continually updated publicly by its original author, and also due to the current stalled state of Plover development, where suggestions for additions to `main.json` by the wider Plover community are stuck in limbo (of course this could change in the future).

Therefore, I think it's okay to continue to have current `main.json` be at the heart of Typey Type, with any custom changes necessary that make life easier for beginners (like removing potentially confusing mis-strokes, adding condensed strokes that are compatible with Plover theory etc), and just continue to allow any user that needs more than that, or wants to use another theory like Lapwing, to upload their own dictionaries for practice, as per what Typey Type can already do.

If `main.json` does end up becoming a real "community" dictionary, with contributors from across the userbase being accepted, then the issue of keeping in sync with it can potentially be re-visited.

**Comment by didoesdigital** [comment]
Thanks for sharing your thoughts here @paulfioravanti. I've been mulling over it and potential implications of what it means if Typey Type lessons and stroke hints are not based on the dictionary that ships with Plover. Would I declare a new "Typey Type Plover dictionary" and let it diverge/improve? I was half-way through a branch on the [CLI](https://github.com/didoesdigital/typey-type-cli) exploring some ideas of what `wontfix`-ing this could mean before replying and then life got in the way!

One key consideration for giving up on trying to keep Typey Type dictionaries in sync with Plover would be to add new briefs:

- Basically anything in `di-briefs.json` could potentially be folded into `dict.json`, which then gets used for the brief solitude-y `typey-type.json` dictionary in the app. (By solitude-y I mean each word has only 1 entry/outline.)
    - Beginners might then run into a word like "exotic" and see my outline `KPOBGT` as the hint and be annoyed that it doesn't work because they're using the Plover `main.json` dictionary that doesn't have it.
        - In which case the UI should then strongly recommend using Typey Type's dictionary.
            - In which case, I should probably produce an actual combined dictionary for daily use that people can download, including more than 1 outline per word
                - In which case the CLI needs should do some extra things like having a sensible sort order
                    - … and this is where I got lost down a rabbit hole! I hope to finish thinking this through soon.

Overall, your reasoning makes sense @paulfioravanti and I really appreciate you laying it out and encouraging a resolution to this issue!

**Comment by didoesdigital** [comment]
Ok! Typey Type now uses only a standard dictionary set from this repo instead of Plover's. There's also a new ["Full Dictionary"](https://didoesdigital.com/typey-type/dictionaries/typey-type/typey-type-full/) available as a single download for that set to use directly instead of `main.json`.

I've updated this repo's README, the [Typey Type dictionaries page](https://didoesdigital.com/typey-type/dictionaries), and the [Typey Type About page](https://didoesdigital.com/typey-type/support#typey-type-dictionary) to recommend people use the Typey Type dictionary instead of Plover's. I hope this will minimise complaints about differences between Typey Type hints and Plover entries.

We will no longer bother trying to "avoid getting ahead of releases of the Plover dictionary with Plover app releases". I officially declare this issue closed!

Thanks again for the nudge @paulfioravanti . And thanks again for all of your contributions to this repo over the years! It wouldn't have been possible to get to this point without you.
