### ISSUE TITLE
No Plover stroke for "diseased"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#111]
In the current `dict.json` and `top-10000-project-gutenberg-words.json` dictionaries, the entry for "diseased" is:

```json
"STKAOEFD": "diseased"
```

However, there does not seem to be a stroke entry for "diseased" at all in in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33).

I'm assuming that to fix this issue in the dictionaries, `"STKAOEFD": "diseased"` should be added to `bad-habits.json`, but I'm not entirely sure what would be a good stroke to replace it with in `dict.json` and `top-10000-project-gutenberg-words.json`:

- Fingerspelling? (`TK*/*EU/S*/*E/A*/S*/*E/TK*`)
- Two-stroke? (`STKAOES/-D`, to be similar to the `"STKAOESZ": "diseases"` entry in `top-10000-project-gutenberg-words.json`)
- Something else...?

**Comment by didoesdigital** [comment]
It looks like `"STKAOEFD": "diseased"` used to exist in Plover's dictionary but was replaced in [this giant commit with the message "Update dictionary with feedback from issue 400"](https://github.com/openstenoproject/plover/commit/06def59686203707cc5700e3fa39ef7fb297d6f5) where the comments have been deleted so there's no recorded history of why it was changed.

In the current dictionary, I can see the following entries:

```
"STKAOE": "disease",
"STKAOED": "disease",
"STKAOEF": "deceive",
"STKAOEFD": "deceived",
```

I would guess from this that `STKAOEFD` was preferred for `deceived` instead of `diseased` for some reason, and `"STKAOED": "disease",` is probably meant to be `"STKAOED": "diseased",` but is missing the trailing "d".

We could: 

- Update `dict.json` to use `"STKAOE": "disease",`
- Add a `condensed-strokes.json` entry for `"STKAOE/-D": "diseased",`
- Update the `top-10000-project-gutenberg-words.json` entry to use `"STKAOE/-D": "diseased",`

**Comment by paulfioravanti** [comment]
Sounds like a good plan to me. I'll put in a PR that makes those changes.

**Comment by didoesdigital** [comment]
Ah, thanks for clarifying @paulfioravanti. I was mistaken and meant `dict.json` without realising it was already fine. Updating `top-10000-project-gutenberg-words.json` to use `"STKAOE": "disease"` makes sense though.

I also just noticed `"STAOES": "disease",` missing "K" should move into `bad-habits.json`.
