### ISSUE TITLE
No entry in Plover for "continues"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#129]
In the current `dict.json` and `top-10000-project-gutenberg-words.json` dictionaries, the entry for "continues" is:

```json
"T-PBS": "continues"
```

https://github.com/didoesdigital/steno-dictionaries/blob/f1933916514da3cea924d941a2d8bb82ca56ce71/dictionaries/top-10000-project-gutenberg-words.json#L4785

However, there does not seem to be a specific stroke entry for "continues" at all in in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33).

I'm assuming that there was an entry of `"T-PBS": "continues"` in the past that has since been removed, or that it's perhaps a typo for `"T-PB/-S": "continues"`(?).

The current output for `T-PBS` is "continuous". The current `dict.json` dictionary entries for "continuous" are:

```json
"KOPB/TEUPB/KWROUS": "continuous",
"KOPB/TEUPB/OUS": "continuous",
"KOPB/TEUPB/WOUS": "continuous",
"KOPBT/KWROUS": "continuous",
"KOPBT/WOUS": "continuous",
"T-PB/KWRUS": "continuous",
"T-PB/WOUS": "continuous",
```

All of these would seem to be valid in Plover except for `"KOPB/TEUPB/KWROUS": "continuous"`, which does not seem to be present.

The current stroke used in `top-10000-project-gutenberg-words.json` for "continuous" is:

https://github.com/didoesdigital/steno-dictionaries/blob/f1933916514da3cea924d941a2d8bb82ca56ce71/dictionaries/top-10000-project-gutenberg-words.json#L5090

Given that `T-PBS` outputs "continuous", I'm assuming this `top-10000-project-gutenberg-words.json` entry should be changed to its simpler stroke.

So, given all this, I'm not entirely sure of the correct courses of action, but perhaps something like:

- Change "continues" stroke entries in `dict.json` and `top-10000-project-gutenberg-words.json` from `T-PBS` to `T-PB/-S` (or whatever is the more appropriate stroke)
  - (Should `"T-PBS": "continues"` go into `bad-habits.json`...?)
- Add `"T-PBS": "continuous"` to `dict.json`
- Remove `"KOPB/TEUPB/KWROUS": "continuous"` from `dict.json`
  - (Add `"KOPB/TEUPB/KWROUS": "continuous"` to `bad-habits`...?)
- Change "continuous" stroke entry in `top-10000-project-gutenberg-words.json` from `T-PB/WOUS` to `T-PBS`

**Comment by didoesdigital** [comment]
Thanks for working through this, @paulfioravanti. Following your suggestions, here's what I think we should do:

- Change "continues" stroke entries in `dict.json` and `top-10000-project-gutenberg-words.json` from `T-PBS` to `T-PB/-S`.
- Add `"T-PB/-S": "continues"` to `condensed-strokes.json`.
- Don't add `"T-PBS": "continues"` to `bad-habits.json` so that we avoid it overriding "continuous" for people that use `bad-habits.json` after the main dict.
- Add `"T-PBS": "continuous"` to `dict.json`.
- Remove `"KOPB/TEUPB/KWROUS": "continuous"` from `dict.json`.
- Add `"KOPB/TEUPB/KWROUS": "continuous"` to `bad-habits.json`.
- Change "continuous" stroke entry in `top-10000-project-gutenberg-words.json` from `T-PB/WOUS` to `T-PBS`.
