### ISSUE TITLE
Issue with stroke for "remaining"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#130]
In the current `dict.json` file, there are the following strokes for the word "remaining", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"RAOE/PHAEUPBG": "remaining",
"RE/PHAEPBG": "remaining",
"RE/PHAEUPB/-G": "remaining",
"RE/PHAEUPBG": "remaining",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke for "remaining" used is:

https://github.com/didoesdigital/steno-dictionaries/blob/f1933916514da3cea924d941a2d8bb82ca56ce71/dictionaries/top-10000-project-gutenberg-words.json#L2059

Although Plover says it's a valid stroke, I feel that `"RE/PHAEUPBG": "remaining"` with the elongated "ā" sound (`AEU`) is a more accurate entry pronunciation-wise (and all the other entries use `AEU`), and so would like to propose:

- Removing `"RE/PHAEPBG": "remaining"` from `dict.json`
- Adding `"RE/PHAEPBG": "remaining"` to `bad-habits.json`
- Changing the stroke for "remaining" in `top-10000-project-gutenberg-words.json` from `RE/PHAEPBG` to `RE/PHAEUPBG`

**Comment by didoesdigital** [comment]
Thanks for this @paulfioravanti.

Adding to your thoughts, `PHAEPBG` also exists for `messenger`. There are no entries for  `"PHAEPBG": "maining"` to match `RE/PHAEPBG": "remaining"` without the `RE/` prefix or `"RE/PHAEPBG": "remessenger",` to match `"PHAEPBG": "messenger",` with the `RE/` prefix.

Your suggested changes sound good to me (except where you said "completely" instead of "remaining", which I assume you copied from https://github.com/didoesdigital/steno-dictionaries/issues/104).

**Comment by paulfioravanti** [comment]
Heh, you got me on the copy/paste 😊I only do it so that each one of these issues can be read in isolation should someone (or future me) google it in the future. I'll put in a PR covering the changes outlined.
