### ISSUE TITLE
Issue with stroke for "convey"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#133]
In the current `dict.json` file, there are the following strokes for the word "convey", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"KAUP/SRAEU": "convey",
"KAUPB/SRAEU": "convey",
"KAUPB/SREU": "convey",
"KOPB/SRAEU": "convey",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "convey" is:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L3343

Although Plover says `"KAUPB/SREU": "convey"` is a valid stroke, I feel that either `"KAUPB/SRAEU": "convey"`, with the elongated "ā" (or `"KOPB/SRAEU": "convey",` if `KAUPB` can be replaced with `KOPB` for "con") is a more accurate entry pronunciation-wise.

Given that all the entries in `dict.json` that include "convey" use `AEU`:

```json
"KAUPB/SRAEUD": "conveyed",
"KAUPB/SRAEUG": "conveying",
"KAUPB/SRAEUPBS": "conveyance",
"KAUPB/SRAEUR": "conveyor",
"KOPB/SRAEU/ER": "conveyer",
"KOPB/SRAEU/KWRAPBS": "conveyance",
"KOPB/SRAEU/KWRER": "conveyer",
"KOPB/SRAEU/KWROR": "conveyor",
"KOPB/SRAEUPBS": "conveyance",
"TKAUPB/SRAEU/-D": "conveyed",
```

As well as the entries that include "convey" in `top-10000-project-gutenberg-words.json`:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L4234

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L9335

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L9501

I would like to propose:

- Removing `"KAUPB/SREU": "convey",` from `dict.json` (and maybe also `"KAUP/SRAEU": "convey",` since it drops the `B` for the "n" (`PB`) sound in "con")
- Adding `"KAUPB/SREU": "convey",` (and maybe also `"KAUP/SRAEU": "convey",`) to `bad-habits.json`
- Changing the "convey" entry in `top-10000-project-gutenberg-words.json` from `KAUPB/SREU` to `KAUPB/SRAEU` (or `KOPB/SRAEU` depending on what your feelings are about `KOPB` for "con")

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti. Those changes, including removing the entries missing the `B` in `PB`, sound good to me.

On the point of `KAUPB/SRAEU` vs `KOPB/SRAEU`, I have mixed feelings. I wrote about [Understanding prefixes](https://didoesdigital.com/project/plover/#understanding-prefixes), finishing up with "you can form words using prefixes that may not need their own dictionary entries, and not all words starting with common beginnings are actually using prefixes". Some further considerations:

- `KAUPB` is the correct prefix in Plover theory.
- `KOPB` could be there as a misstroke OR because it's the preferred stroke in Magnum theory (or so I've heard) OR possibly for words that phonetically start with a "con" sound but aren't really using a prefix like `"KOPB/-BG": "conk",`.
- I have a note from stenoknight on the Plover Discord 06/10/2019 saying, "We should batch remove all the KON strokes".
- There are some entries for words starting with `KOPB/` that don't have a `KAUPB/` equivalent and would need to be added if the `KOPB/` versions were bulk removed.

For this Issue, I suggest using `KAUPB/SRAEU` for "convey".
