### ISSUE TITLE
Issue with strokes for "bestow*"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#134]
In the current `dict.json` file, there is the following stroke for the word "bestow", which is valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PWE/STOEU": "bestow",
```

This stroke is also used in the `top-10000-project-gutenberg-words.json` dictionary:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L5376

It would seem that there is a new stroke for "bestow" that has been added by Plover, which I personally think is a better pronunciation match than `PWE/STOEU`":

```
bestow:
   PWES/TOE
```

At the very least, I would propose:

- Add `"PWES/TOE": "bestow",` to `dict.json`

But, since I think that it's overall a better stroke, I'd also like to propose:

- Change the `top-10000-project-gutenberg-words.json` entry for "bestow" from `PWE/STOEU` to `PWES/TOE`
- Change the `top-10000-project-gutenberg-words.json` entry for "bestowed" from `PWE/STOEU/-D` to `PWES/TOE/-D`

If, given the new stroke for "bestow", the `"PWE/STOEU": "bestow"`stroke should now be considered a mis-stroke, then I'd also propose:

- Remove `"PWE/STOEU": "bestow"` from `dict.json`
- Add `"PWE/STOEU": "bestow"` to `bad-habits.json`

I do think, however, that there is an argument to be made to _only_ add `"PWES/TOE": "bestow",` to `dict.json` and leave everything else as-is, which is that other strokes that have "bestow" in them which Plover has entries for, start with `PWE/STOE` (but do not use `U`):

```json
"PWE/STOE/WAL": "bestowal",
"PWE/STOEBL": "bestowable",
"PWE/STOEL": "bestowal",
"PWE/STOEPLT": "bestowment",
```

Given all this, what do you think the best course of action is?

**Comment by didoesdigital** [comment]
Thanks for sharing all of those details @paulfioravanti. This change sounds good:

- Add `"PWES/TOE": "bestow",` to `dict.json`

`"PWE/STOEU": "bestow",` also uses a prefix stroke, `"PWE": "{be^}",`. Generally, entries using proper prefix and suffix strokes are better because they're more predictable and less likely to cause word boundary errors. In this case, `STOEU` is a brief or misstroke for `"study"` and NOT the stroke for `"stow"` (which is stroked `STOE`), so the prefixed entry for "bestow" is less convincing than prefixed entries usually are.

On the balance, I think the consistency with "bestowal", "bestowable", and "bestowment", is worth keeping "everything else as-is".
