### ISSUE TITLE
Confusion over stroke for "upstairs"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#135]
In the current `dict.json` file, there is the following stroke for the word "upstairs", which is valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"AOUP/STAEUR/-S": "upstairs",
```

The `top-10000-project-gutenberg-words.json` dictionary would seem to use a different stroke for "upstairs":

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L3789

The `top-10000-project-gutenberg-words.json` stroke of `"AUP/STAEURS": "upstairs"` would seem to come from the `condensed-strokes.json` dictionary, as it's not present in Plover:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/condensed-strokes.json#L775-L776

But it would also seem to come as a result of [this commit](https://github.com/didoesdigital/steno-dictionaries/commit/d05a568a14172a839cdf645b0b3a326acb2c7030), which "update[d] lots of briefs to prefer `AUP` for up^ over `UP/`"

Plover itself lists the following strokes for "upstairs"...

```
upstairs:
   UP/STA*EURS
   UP/STAEUR/-S
   AOUP/STAEUR/-S
```

...even though that Plover itself would seem to agree with preferring `AUP` for up^ over `UP/` as its entries for up^ are:
  
```
{up^}:
   AUP
   KWRUP
```

The top two strokes in Plover's list are marked as mis-strokes already due to the commit mentioned previously:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/bad-habits.json#L288-L289

Which leaves `"AOUP/STAEUR/-S": "upstairs",` as being the only stroke that the dictionaries and Plover would seem to agree are valid.

So, my questions are:

- Should the `top-10000-project-gutenberg-words.json` stroke for "upstairs" be changed from `AUP/STAEURS` to `AOUP/STAEUR/-S` to match Plover?
- Or, is the custom condensed stroke fine, and no action needs to be performed?

`AOUP` for "up" does read a bit strange to me, so it may also read strange to others if it appears in Typey-Type, though the `AUP` "awp" sound for "upstairs" also read strangely, which is what prompted me to look into this in the first place.

**Comment by paulfioravanti** [comment]
A similar issue exists for the stroke for "upright":

Plover says:

```
upright:
   UP/RAOEUGT
   UP/RAO*EUGT
```

The dictionaries say they're both mis-strokes:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/bad-habits.json#L273-L274

And instead uses a custom entry in `top-10000-project-gutenberg-words.json`...

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/top-10000-project-gutenberg-words.json#L3729

...which seems to come from the `condensed-strokes.json` dictionary:

https://github.com/didoesdigital/steno-dictionaries/blob/244fcfac9e1cc2f5a37a9fdd27a4f27b26a77507/dictionaries/condensed-strokes.json#L760

**Comment by didoesdigital** [comment]
That's a lot of detective work, @paulfioravanti! Well done, and thanks for putting this together.

As you pointed out, Plover uses `AUP` as a prefix stroke with the entry, `"AUP": "{up^}",`. As I noted recently, "you can form words using prefixes that may not need their own dictionary entries", with the details expanded on in [Understanding prefixes](https://didoesdigital.com/project/plover/#understanding-prefixes). In practice, this often means the Plover dictionary doesn't include entries that would be considered the "correct" entry for Plover theory because you can already write it using the prefix stroke and the base word without an explicit entry, as is the case with `"AUP/STAEURS": "upstairs",`.

It's my personal preference to go overboard with adding all such words to the `condensed-strokes.json` dictionary because it improves the lookup experience. The explicit entries using the correct prefix, however, wouldn't necessarily make sense as additions to the core dictionary (where they would add bloat and contribute to performance issues).

Likewise `"AUP/RAOEUGT": "upright",` uses the correct prefix stroke and matches the entry for `"RAOEUT": "right",`.

**Comment by paulfioravanti** [comment]
Thanks so much for that explanation, @didoesdigital! Yet again, I'm learning lots! I'm going to assume, then, that no further action needs to be taken on this issue, so I'll close it out.
