### ISSUE TITLE
Stroke for "monkey" missing `O` stroke for "ē" sound

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#211]
In the current `dict.json` file, there are the following strokes for "monkey", all of which are valid in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33):

```json
"PHO*PBG/KAOE": "monkey",
"PHOPB/KAE": "monkey",
"PHOPB/KAOE": "monkey",
"PHOPB/KEU": "monkey",
"PHOPBG/KEU": "monkey",
"PHOPBG/KWREU": "monkey",
```

In the `top-10000-project-gutenberg-words.json` dictionary, the stroke used for "monkey" is:

https://github.com/didoesdigital/steno-dictionaries/blob/ef6a38a679db5a27769e0c9e2116f2d02a09165f/dictionaries/top-10000-project-gutenberg-words.json#L6982

`"PHOPB/KAE": "monkey"` without an `O` stroke to form the "ē" sound of "monk*ey*" looks like a mis-stroke to me, so I would like to propose:

- Removing `"PHOPB/KAE": "monkey"` from `dict.json`
- Adding `"PHOPB/KAE": "monkey"` to `bad-habits.json`
- In `top-10000-project-gutenberg-words.json` change:
  - before: `"PHOPB/KAE": "monkey"`
  - after: `"PHOPB/KAOE": "monkey"` (or maybe `"PHOPB/KEU": "monkey"`, depending on whether you think "monkey" has a long "ē" sound or not)

**Comment by didoesdigital** [comment]
Thanks @paulfioravanti . I've noticed a lot of suffixes ending with "y" use `EU` in their stroke such as:

```
"REU": "{^ry}",
"SEU": "{^cy}",
"HREU": "{^ly}",
```

So I would have expected to see `KEU` used for "monkey". Instead, it's occupied by `"KEU": "can I",`

It turns out there exists a suffix entry: `"KAE": "{^key}",`. Given `PHOPB` successfully writes "mon", using `KAE` to add "key" seems sensible enough. Let's keep these entries as they are.

**Comment by paulfioravanti** [comment]
TIL the `"KAE": "{^key}"` suffix! Thanks, @didoesdigital! Agreed to keep this stroke as-is.
