### ISSUE TITLE
Question about stroke for "father's"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#22]
Currently, in both Plover and in the repo dictionaries, the stroke for "father's" is `TPA*ER/AES`. This stroke is, of course, correct, but I'm just curious if I'm missing something with regards to how it is formed. What I mean by that is:

- `TPA*ER` outputs "fare", and then stroking `AES` transforms it into "father's"
- `TPAER` outputs "father", and then stroking `AES` after that, you get the same "father's"

I would have thought that `TPAER/AES` would be a better stroke for "father's" since:

- it removes a single keystroke
- the building blocks of `"father" + "'s" = "father's"` is, at least for me, easier than `"fare" + "'s" = "father's"`

Is there a steno logical rule I'm missing? If not, would this be a potential candidate for a PR to improve on the Plover entry for Typey Type?

**Comment by didoesdigital** [comment]
I agree, @paulfioravanti, `TPAER/AES` would be a better stroke for "father's". My guess is that `TPA*ER/AES` is a misstroke entry for `TPAER/AES`. We might then move it into `bad_habits.json`.

You can already use `TPAER/AES` for "father's" because the word `"TPAER": "father",` and the suffix `"AES": "{^'s}",` already exist. Plover's dictionary often won't bother with explicitly adding these entries. Too many of them would harm performance when opening Plover and loading dictionaries.

In these cases, I add the combined entry (in this case: `"TPAER/AES": "father's",`) to the `condensed-strokes.json` dictionary so that it appears in searches and in Typey Type lessons. Do you want to make a PR for that?

**Comment by paulfioravanti** [comment]
Having a deeper look into the dictionaries, I can see that `TPAER/AES` is used already in `condensed-strokes.json`, and `top-10000-project-gutenberg-words.json` (which is where I would have thought Typey Type would be getting its words from for the exercises I've been doing):

https://github.com/didoesdigital/steno-dictionaries/blob/380088250ffca0e878d9b88bc21f2b0748baad0e/dictionaries/condensed-strokes.json#L107

https://github.com/didoesdigital/steno-dictionaries/blob/380088250ffca0e878d9b88bc21f2b0748baad0e/dictionaries/top-10000-project-gutenberg-words.json#L1005

`TPA*ER/AES` is used in `dict.json:122674`, though, but I'm assuming that since the entry is not a mistake, you'd rather keep that the way it is. So, I'm not sure where to put the entry now in order to get Typey Type to pick it up. How should this change be made?

**Comment by didoesdigital** [comment]
Ah, I see what's happening. This is due to some awful, hard-coded entries I added to the back-end static lesson generator code to workaround it failing to match words with apostrophes properly. I can fix that. My aim is to bring all the lesson generator code to Typey Type's front end to replace the buggy cruft and make it easier for people to create their own lessons from their own dictionaries (or at least be perfectly in sync with this repo).

Thanks for having a deeper look to identify that. I hope you didn't go on too much of a wild goose chase to find it.

Happy for to close this?

**Comment by paulfioravanti** [comment]
Yep, happy to close this, and happy that it led to some fixes :)
