### ISSUE TITLE
Question about asterisk-ed suffixes

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#288]
Following on from #286, before I submit any further pull requests similar to it, could I please clarify if there should be any general rule to follow when:

- A Plover outline uses an asterisk-ed suffix (eg `*FD`, `*PBS`)
- Yet, if you omit the asterisk in the suffix, output is still as expected

Can the asterisk be validly omitted if the output is correct, or is it generally considered good form to learn the suffixes with asterisks if they are the only entry in Plover?

More examples I have found recently of this are:

- "dissolved"
  - current stroke: `TKEUS/SOL/*FD`
  - condensed stroke that works: `TKEUS/SOL/FD`
- "holiness"
  - current stroke: `HOE/HREU/*PBS`
  - condensed stroke that works: `HOE/HREU/PBS`
- "loveliness"
  - current stroke: `HR*UF/HREU/*PBS`
  - condensed stroke that works: `HRUF/HREU/PBS`
- "frankness"
  - dictionary stroke: `TPRAPBG/*PBS`
  - condensed stroke that works: `TPRAPBG/PBS`
- "friendliness"
  - dictionary stroke: `TPREPBD/HREU/*PBS`
  - condensed stroke that works: `TPREPBD/HREU/PBS`

Would these strokes be considered valid candidates for condensed strokes, and also for use in  the Gutenberg dictionary?

**Comment by didoesdigital** [comment]
Great question, @paulfioravanti !

The short version: for condensed strokes and Gutenberg dictionary, we mostly want the version that best matches the intended suffix strokes, where intended suffix strokes may or may not use an asterisk.

Let's add:

```
"TPRAPBG/-PBS": "frankness",
"TPREPBD/HR*EUPBS": "friendliness",
"HROFL/-PBS": "loveliness",
"HOEUL/-PBS": "holiness",
"TKEUS/SOFLD": "dissolved",
```

---

From the [Learn Plover book](https://sites.google.com/site/learnplover/lesson-5-prefix-and-suffix-strokes#TOC-What-Are-Prefix-And-Suffix-Strokes-):

> Many suffixes are distinguished from word parts by adding the `*`; the word 'on' is `OPB`, while the '-on' suffix as used in a word like 'mutton', is `O*PB`. Many prefixes are distinguished from word parts by altering the vowels; the 'on-' prefix as used in a word like 'onramp', is `AUPB`. But these are not universal rules. As you learn more prefix and suffix strokes, you may recognize more of the patterns behind them. If you're ever unsure about how to make a prefix or suffix, consult the dictionary file.

Generally, true suffix entries usually use an asterisk and are usually safer/more reliable to use. Phonetic entries sometimes exist as well without using the asterisk and, where that works, is more convenient to write at speed (less travel for your fingers). As an example, consider these entries:

```
"-PB": "an",
"*PB": "{^n}",
"EPB": "{en^}",
"*EPB": "{^en}",
```

Despite the proper suffix strokes `*PB` and `*EPB`, you'll find loads of entries in the Plover dictionary for words ending in "en" or "in" that finish with `/EPB` or `/-PB`. For example:

```
"KAUF/-PB": "coffin",
"KEUT/-PB": "kitten",
"KHOEZ/-PB": "chosen",
"KPAPL/-PB": "examine",
"PHAEUD/EPB": "maiden",
"PWROEBG/EPB": "broken",
```

I wouldn't necessarily mark these as misstrokes, but I also wouldn't add any of these as new entries to the condensed strokes dictionary because they are not using the correct suffix strokes.

Looking at the particular examples you cited…

Note these relevant suffix entries in the dictionary (especially the extra "i" in the second line):

```
"-PBS": "{^ness}",
"*PBS": "{^iness}",
"HR*EUPBS": "{^liness}",
```

I suspect "frankness" using `TPRAPBG/*PBS` is actually a misstroke entry, auto-correcting it to remove the "i". A condensed stroke and entry in project gutenberg for `TPRAPBG/-PBS` would be great.

Along a similar vein, "holiness", "loveliness", and "friendliness" using the asterisk-ed strokes are explicit entries using a redundant "i" sound between the "i" sound in the previous stroke `/HREU` and the "i" in `"*PBS": "{^iness}",`. I'd prefer `/-PBS` to append "ness", though that depends on the orthography rules to fix the spelling. Even better would be to use the `"HR*EUPBS": "{^liness}",` suffix e.g. `TPREPBD/HR*EUPBS` for friendliness. For these words, condensed strokes and entries in project gutenberg would be great.

Note, there's also a brief for "lovely" using `HROFL`. Here, you can append `/-PBS` to produce "loveliness", but using `/*PBS` incorrectly produces "lovelyiness" (if I have the right dictionaries turned on/off).

Side note: a reminder that when you are writing right-hand only strokes, it's standard to include a dash e.g. `TPRAPBG/PBS` should be written as `TPRAPBG/-PBS`. This is important for keys that are written on both sides like `P` or `-P`, `S` or `-S`, etc.

"dissolved" looks like an exception to me. Using the entries for `"SOL/-F": "solve",` and `"SOL/*F": "solve",` as well as the prefix entry `"TKEUS": "{dis^}",`, you can write "dissolve". The [`-D` suffix key uses Plover's special suffix key behaviour](https://sites.google.com/site/learnplover/lesson-7-orthography-rules-and-suffix-keys) (this is a new page I added recently), to tuck it into the previous stroke, as if you'd stroked `TKEUS/SOL/-F/-D` and uses the suffix entry `"-D": "{^ed}",` to append "ed", effectively writing "dissolveed", then the orthography rules remove the extra "e". The fact that it works with or without the `*` in the `F` stroke is more to do with the "F key as 'v' sound" rule and the inconsistent use in the dictionary of whether the asterisk-ed version gets priority as the 'f' or 'v' or 's' sound. I think these days I prioritise `F` as 'f' and `*F` as 'v', so I'd prefer `TKEUS/SOL/*FD` over `TKEUS/SOL/FD` for dissolved, but there also exists `"SOFL": "solve",` and `"SOFLD": "solved",` using inversion, so I'd add a condensed stroke entry for `TKEUS/SOFLD`.

For Typey Type and adding strokes to the condensed strokes dictionary or the gutenberg dictionary, I think we can use generally choose the asterisk-ed or un-asterisk-ed version based on whether it's the most accurate suffix stroke. This sticks to the ideas we nutted out in https://github.com/didoesdigital/steno-dictionaries/issues/41, where we want to give new stenographers greater confidence in learning new briefs by prioritising the shortest entry, with penalties for entries with more slashes/strokes or asterisks, or words with prefixes/suffixes that aren't using the correct prefix/suffix stroke, accepting that there'll be some exceptions to consider case-by-case because English is full of quirks and steno theory is malleable.

**Comment by paulfioravanti** [comment]
Thank you so much for this write-up @didoesdigital. I _really_ appreciate the time and effort it took to address everything in such detail.

I'll get in a PR that adds in that set of condensed strokes you outlined above:

```
"TPRAPBG/-PBS": "frankness",
"TPREPBD/HR*EUPBS": "friendliness",
"HROFL/-PBS": "loveliness",
"HOEUL/-PBS": "holiness",
"TKEUS/SOFLD": "dissolved",
```
