### ISSUE TITLE
On using the shortest stroke for entries in Typey-Type even if it's a shortcut

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#41]
As a steno learner who is trying to gain as much muscle memory as possible by mapping key strokes to letters/sounds in my head, sometimes I'll come across entries in Typey-Type like:

```json
"THRAOUD": "fluid",
"TPALT": "fault",
"HREBSZ": "lenses"
```

Each of these strokes is the shortest stroke for its word, but it would seem that they are also shortcuts.

What this means for me is that, for example, when I see `THRAOUD` for "fluid" come up, but I'm expecting `TPHRAOUD` with the full `TP` for the "f" sound, like I see with many other words, I inadvertently stop and wonder if this is an irregular or special stroke, and then test the word with the longer stroke I'm expecting, given how I'm pronouncing the word in my mind. If the more detailed stroke proves to be correct, I will mentally adjust to use that stroke in the future, since remembering shortcuts at is, for me at least, mental overhead that I don't want to deal with at this point. 

My question is, therefore, should Typey-Type prioritise the shortest stroke for an entry in _all_ cases, or should it prioritise consistency to help build muscle memory, and then when a beginner graduates to intermediate and above, they can then make their own decisions on whether they want to use shortcuts? The answer to this question could also help to inform future pull requests as well.

**Comment by didoesdigital** [comment]
Hey @paulfioravanti. Great question. 

These particular examples all happen to be misstrokes. "fluid" is missing a `P`, "fault" is missing a `U`, and "lenses" is missing a `P`. From #3 for removing prominent misstrokes:

> The aim is to remove all the misstrokes from `dict.json` to give new stenographers greater confidence in learning new briefs.
> The first step is to remove all the misstrokes for the _shortest_ available brief for every word, starting with words appearing in Typey Type's top 10,000 words lessons.

So we should remove those entries.

To your question about prioritising consistency over shortness, I have a few thoughts.

- There are different kinds of consistency to think about so we'd need to clarify that. For example: consistent with canonical Plover theory, consistent with sets of entries like [mountain*](https://github.com/didoesdigital/steno-dictionaries/issues/26#issuecomment-449797097), consistent with a specific version of Plover dictionary, and so on. Consistency is harder to think about than shortness.
- There are different kinds of shortness to think about so we'd need to clarify that. There's shortness in briefs, which might diverge wildly from theory, then there's shortness than might be only 1 key different, such as all the [double 's' words that have entries using `S` as well as `SZ`](https://github.com/didoesdigital/steno-dictionaries/issues/30#issuecomment-475434225).
- Some people value fewer keys really highly, like this [set of outlines for writing the top 1000 words in 1 stroke and 6 or fewer keypresses](https://www.reddit.com/r/Plover/comments/7by4un/a_set_of_outlines_for_writing_the_top_1000/).
- Some people value strokes with the least reach/travel really highly, or the fewest contortions and risk of misstrokes. 
- Some people prefer learning briefs early on so they don't memorise the long form version and never discover that a brief exists for a word.
- Some people prefer to guess at long form versions of entries than fingerspell words they're unsure about.
- Some people prefer to guess at long form versions of many entries than memorise briefs for fewer entries while they're starting out.
- Some people prefer to learn sets of entries that follow a similar pattern than a specific, preferred outline for each entry. Again, like the like [mountain*](https://github.com/didoesdigital/steno-dictionaries/issues/26#issuecomment-449797097) example.
- Some of the above depends on why you're using steno e.g. for ergonomic day-to-day typing vs fast, accurate live dictation,.

At the moment, Typey Type ranks outlines by "shortest" stroke with penalties for entries with more slashes/strokes, asterisks, or words with prefixes/suffixes that aren't using the correct prefix/suffix stroke. My intention is for the "shortest" stroke to never be a misstroke.

Overall, I think the Typey Type should prioritise the shortest entry (considering the penalties above) that is not a misstroke, accepting that there'll be some exceptions to consider case-by-case because English is full of quirks and steno theory is malleable.

What are your thoughts?

I've been thinking more about how to present more than one option for how to stroke a word in Typey Type, which might minimise the need to answer some of these questions.

**Comment by paulfioravanti** [comment]
Thanks so much for this detailed and thoughtful answer, Di.

It would seem that the premise of my having opened this issue was probably mistaken due to my still very limited steno experience: what looked to me like briefs were actually mis-strokes.

So, first, given the following mis-strokes,

```json
"THRAOUD": "fluid",
"TPALT": "fault",
"HREBSZ": "lenses"
```

I'll open a PR that:

- moves them to `bad-habits.json`, since they all still work in Plover, and
- changes the current entries to their correct strokes of:

```json
"TPHRAOUD": "fluid",
"TPAULT": "fault",
"HREPBSZ": "lenses"
```

> Overall, I think the Typey Type should prioritise the shortest entry...that is not a misstroke, accepting that there'll be some exceptions to consider case-by-case because English is full of quirks and steno theory is malleable.

I can definitely agree with this: the less correct strokes, the better. I'll also make sure to consider the possibility that what I'm seeing as a brief may actually be a mis-stroke, and open an issue here if I'm not sure. 

Given your list of thoughts above, and the amount of points that would seem to be up to personal preference and can't be determined to be objectively right or wrong, I don't think I can currently come up with a policy that would be better than what Typey-Type currently has, until, perhaps, something becomes a pain point in the future.

So, I'm happy to have this issue closed unless there is room for more discussion.

**Comment by didoesdigital** [comment]
Thanks for following up @paulfioravanti . Those PR changes sound good. I'll close the issue for now.
