### ISSUE TITLE
Homophones exercise using many entries from di-nouns.json

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#510]
In the Homophones Typey Type exercise, I've found that there are quite a few entries used in there that are personal briefs from `di-nouns.json`. So far, specifically, I've found:

```
"HRA*EUZ": "laze"
"PHO*ET": "mote"
"WRAPT": "wrapt"
"KOPB/TEUPB/SKWREPBS": "contingence"
"SKWR*EL": "jell"
"A*DZ": "adz"
"A*DZ/SKWRE": "adze"
```

There does not seem to be Plover entries for these words, and I couldn't figure out any condensed strokes for them.

So, should the advice for doing certain lessons in Typey Type be to download and use the `di-nouns.json`? I notice that in the Homophones [lesson dictionary](https://github.com/didoesdigital/typey-type-data/blob/master/lessons/drills/homophones/homophones.json), there are entries marked with an "xxx" prefix. Was this meant to tell Typey Type to perhaps skip over these entries? If so, I can confirm that they still appear 😄 

For the time being, perhaps, would it be worth adding explicit finger spelling condensed stroke entries for all the "xxx"-prefixed entries?

**Comment by didoesdigital** [comment]
Thanks for filing this issue @paulfioravanti 

The "xxx" appears when the static lesson generator was unable to automatically generate a stroke for the word. It makes them easier to identify for fixing, but there are loads of them. You're welcome to make up your own briefs to add to `di-nouns.json` if you wanted to use that personally. Otherwise, we can add fingerspelling entries to condensed strokes dict (or otherwise assemble condensed strokes).

I am working towards a few features that would make use of a "recommended dictionaries set" concept to point out when a lesson needs certain dictionaries. This lesson could be a good candidate.

**Comment by paulfioravanti** [comment]
> Otherwise, we can add fingerspelling entries to condensed strokes dict (or otherwise assemble condensed strokes).

Is it worth creating a `condensed-strokes-fingerspelled.json` dictionary specifically to isolate words where we know that there are gaps in Plover's dictionary and the current Plover building blocks for outlines do not have a good solution? Or, is it fine to continue to have these entries live in `condensed-strokes.json`?

**Comment by didoesdigital** [comment]
Sounds like a good idea @paulfioravanti ! That might make it easier for people to leave out the fingerspelling dict if it causes them conflicts.

**Comment by paulfioravanti** [comment]
Since [`condensed-strokes-fingerspelled.json`](https://github.com/didoesdigital/steno-dictionaries/blob/master/dictionaries/condensed-strokes-fingerspelled.json) now exists, I don't think this issue has anything else to follow up on, so I'll close it.
