### ISSUE TITLE
Clarification request on specifying "TKPWRUFRP": "grump" as a mis-stroke

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#555]
Could I ask for a clarification on why `"TKPWRUFRP": "grump"` is considered a mis-stroke?

https://github.com/didoesdigital/steno-dictionaries/blob/2dadb6f09421d3a56a93f05cf0fb17227fad1e3b/dictionaries/misstrokes.json#L3432

Although `*PL`  is [the main way to write words ending in "-mp"](https://www.artofchording.com/compounds/mp.html#mp), since Plover also [includes the `-FRP` convention](https://www.artofchording.com/compounds/mp.html#frp-for-mp), I would assume words that use it to still be considered valid. Is there another reason I am missing?

**Comment by didoesdigital** [comment]
`git log -S'grump' -- dictionaries/dict.json --follow-parent` shows I removed that entry in 789463255ac1b8b5d82aec635ec77de9ee8074c3 when I bulk removed everything categorised as a "misstroke" from <http://stenoknight.com/plover/ploverlookup/incategory.json>

I don't recall how those ploverlookup entries were first categorised or who made those choices. I would expect it was because `*PL` was considered canon and `-FRP` was considered borrowed from another theory and therefore a misstroke in Plover theory.

I'd be happy to restore "grump" to `dict.json` if you like. Although I believe that commit was made before I came up with the convention of using the `bad-habits.json` dictionary and auto-generating `misstrokes.json` so I should probably move all of those deletions over to `bad-habits.json`.

**Comment by paulfioravanti** [comment]
> I would expect it was because *PL was considered canon and -FRP was considered borrowed from another theory and therefore a misstroke in Plover theory.

Ah, I see. That makes sense. Now that I look a bit deeper, the only reference that I have Plover supports `-FRP` for the "-mp" sound is Art of Chording, as Learn Plover! [only mentions `*PL`](https://sites.google.com/site/learnplover/lesson-3-english-sounds/3e-compound-clusters). I wonder if Mirabai, or Plover practitioners, is particularly opinionated on the StenEd `-FRP` convention being a mis-stroke, or whether it's just begrudgingly supported, and just the _preference_ is for `*PL`...?

Maybe, then, it's worth keeping it as a mis-stroke for now until that question has an answer, since it may open some small flood gates for other outlines.
