### ISSUE TITLE
Obsolete (?) reference to `common-words.json` dictionary

### ISSUE THREAD

**Issue by YannCebron** [didoesdigital/steno-dictionaries#570]
README.MD mentions and links (404) it here

https://github.com/didoesdigital/steno-dictionaries#common-words-dictionary

**Comment by didoesdigital** [comment]
Hmm, that's odd! I can't track down exactly what happened there but I suspect that dictionary got lost in the shuffle when I first open sourced my dictionaries repo and filtered out some files. These days I try to avoid maintaining dictionaries that are subsets of others because it's harder to keep fixes and changes in sync across them and the `common-words.json` dictionary contained a selection of words from the main `dict.json`.

Thanks for letting me know about this @YannCebron . I'll update the README to remove that reference. Did you happen to want that dictionary for any reason? Or just noticed the link was broken?

**Comment by YannCebron** [comment]
I just noticed the broken link. IIRC there is indeed a less for "Common Words" on TT, maybe that's the origin?

**Comment by didoesdigital** [comment]
The README no longer mentions the obsolete dictionary:

<img width="889" alt="screenshot of README where the obsolete dictionary used to be" src="https://user-images.githubusercontent.com/2476974/180761707-75cc57db-2091-4201-b9c0-0bebb86741ad.png">

In the off chance anyone is looking for it, you can fetch it from the lesson: https://didoesdigital.com/typey-type/dictionaries/lessons/drills/common-words/common-words/

Thanks again @YannCebron !
