### ISSUE TITLE
Add "Return key + uppercase" to Punctuation Dictionary

### ISSUE THREAD

**Issue by YannCebron** [didoesdigital/steno-dictionaries#573]
**Goal**
Insert line return and switch to uppercase capitalization. This is very useful for

- poems
- song lyrics
- and probably some other use cases

**Suggested solution**

Add new single-stroke chord `R*R` which inserts `{#Return}{^}{-|}` as "mix" between the two alternatives detailed below.

**Alternatives**
Currently, these two strokes are defined

(1) Return key `R-R`
(2) New paragraph `SKWRAURBGS`

(1) just adds line return without any capitalization, while (2) also adds an _additional unwanted blank line_  and switches capitalization to uppercase due to start of new paragraph.

To achieve the goal, one would need to use `R-R` to insert new line, followed by additional stroke `KPA` to toggle uppercase. Having a single-stroke solution is obviously much better.

**Comment by didoesdigital** [comment]
Awesome! Great suggestion.

It looks like `R*R` is defined as `{#Return}{^}` in Plover's built in [commands dictionary](https://github.com/openstenoproject/plover/blob/master/plover/assets/commands.json#L36), so we could either add an entry for single return and capitalisation to the `punctuation-di.json` dictionary where I put [more opinionated entries](https://github.com/didoesdigital/steno-dictionaries#dis-dictionaries) or use a different outline than `R*R`. I'm leaning towards the former.

It also looks like using `\n` instead of `{#Return}` is the recommended option in newer versions of Plover because they're more "undoable" (as noted in [recent release notes](https://github.com/openstenoproject/plover/releases/tag/v4.0.0.dev11)

So, maybe something like adding in `punctuation-di.json`:

```
"R*R": "{^\n^}{-|}",
```

? What do you think @YannCebron ?

**Comment by didoesdigital** [comment]
> Having a single-stroke solution is obviously much better

🥳

**Comment by YannCebron** [comment]
thanks, works for me!

**Comment by didoesdigital** [comment]
Done! Thanks for this @YannCebron
