### ISSUE TITLE
Surprising "a long" entry

### ISSUE THREAD

**Issue by timon** [didoesdigital/steno-dictionaries#575]
Good night.
I was practicing with Type Racer today, and one of challenges was a quote from some song, which had words "a lingering...". I was surprised to learn that <kbd>AEU</kbd>/<kbd>HREUPBG</kbd> is a brief for "a long" — is this intended?

I noticed this entry in `dict.json`, but `main.json` dictionary from Plover does not have this entry.

This looks like a misstroke because:

- "A long" could be typed as expected with `AEU/HROPBG`
- `EU` usually represents `I`
- Trying to go on with `AEU/HREUPBG/REUPBG` gives  "a long ring", and typing `HREUPBG/REUPBG` gives "lingering" just fine

To make this better, I should this entry could be moved to `misstrokes.json` or removed altogether.

**Comment by didoesdigital** [comment]
Good catch, @timon ! I agree it looks like a misstroke and a rather meddlesome one. It looks like `AEU/HREUPBG` was fixed some time between Plover 2's and 4's `main.json` and not fixed in Typey Type's `dict.json`.

For this sort of issue, I'd typically:

- remove `"AEU/HREUPBG": "a long",` from `dict.json`
- add `"AEU/HREUPBG": "a long",` to `bad-habits.json`
- … and run my private script to automate adding that same entry to the `misstrokes.json` dictionary.

I happen to be working on dictionaries today so I'm happy to add that fix this evening.

**Comment by didoesdigital** [comment]
And [it's done](https://github.com/didoesdigital/steno-dictionaries/compare/cba108d6294f25632e2febd4a5f11d1af4d68799..5f7b5652e8ed8d16fad1b4239ea8a5e459379190)! Thanks for digging into this and filing an issue about it, @timon ! 🙏
