### ISSUE TITLE
No stroke for "notre" without "dame"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#58]
In the dictionaries, there are entries for word "notre" in the following places:

https://github.com/didoesdigital/steno-dictionaries/blob/7d29392d6bb070e60ded753ab5fd85c6906f9962/dictionaries/nouns.json#L222

https://github.com/didoesdigital/steno-dictionaries/blob/ef5681c357435ecfcf8da70121974b861d7eb5aa/dictionaries/top-10000-english-words.json#L9843

Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33) does not have an entry for "notre" outside of being part of the entry for "Notre Dame".

"notre" features in the `top-10000-english-words.json` list, so I'm assuming that the entry itself needs to stay in some form, but the potential questions around it I see are:

- It's not an English word (as far as I know), so is its inclusion in the `top-10000-english-words.json` list correct?
- If it is correct, then should the stroke be changed to finger-spelling (`TPH*/O*/T*/R*/*E`)?
- Should this entry be converted to "Notre Dame" (`TPHORT/TKAPL`)?

**Comment by didoesdigital** [comment]
Great one @paulfioravanti . The top 10000 English words list comes from [Google’s Trillion Word Corpus via Josh Kaufman's typing word list](https://didoesdigital.com/typey-type/support#credits) so I would guess it appears because "Notre Dame" shows up a lot but "dame" by itself also shows up, even more than Notre. I am loath to make exceptions to change the word list but its inclusion in the top English words without "Dame" does seem odd. On the balance, perhaps converted to "Notre Dame" (`TPHORT/TKAPL`) is best here?

**Comment by paulfioravanti** [comment]
A conversion to "Notre Dame" (`TPHORT/TKAPL`) sounds like the most practical compromise to me, too.
