### ISSUE TITLE
A bunch of strokes with stacked `-S` "-s"

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#589]
# Dictionary

I noticed these dictionary entries in:
- `dict.json`

They were found with `grep "{^s " dict.json`

# Misstroked entry or entries
These look like misstrokes:
```json
"AS/HROU": "{^s allow}",
"AS/KWAOEUR": "{^s acquire}",
"AS/RAOEUF": "{^s arrive}",
"HR-Z": "{^s will}",
"KWR-S": "{^s ,}",
"OEPBTS": "{^s onto}",
"OPBS": "{^s on}",
"ORS": "{^s or}",
"PW-S": "{^s about}",
"S-S": "{^s is}",
"SKP-PBS": "{^s and}",
"SKP-TS": "{^s and the}",
"SOS": "{^s so}",
"TPH-S": "{^s in}",
"TPH/-S": "{^s in}",
"TPR-S": "{^s from}",
"W-S": "{^s with}",
"WHOS/SR": "{^s who have}",
"WOS": "{^s would}"
```

These look like misstrokes because:
- All strokes except `KWR-S` are the suffix "s" stacked with a word or a phrase
- `KWR-S` would be "whys" without that entry in the dict.json, where the word "why" is not found in the translation.

# Expected
I would expect the outline to be:
```json
"HR-Z": "wills"
```

I would expect to see that outline because:
- It uses a suffix folded into the stroke.
- It is consistent with the `main.json` dictionary from Plover 3.

# Even better
To make this even better, we could:
- Remove entries completely because they can already be stroked without their own entries. They're not common phrases so they do not need to appear in dictionary look up searches.

**Comment by didoesdigital** [comment]
Thanks @Monniasza ! I appreciate you putting in the effort in this issue and others to improve the steno dictionaries and help people avoid learning misstrokes on Typey Type.

A fair few of these entries look ok to me. It seems like they are using a rare Plover briefing pattern of both folding a suffix stroke into a word and flipping the steno order of them. For example, `TPH-S` lets someone write "noises in" using `TPHOEUS TPH-S` (2 strokes) instead of `TPHOEUS/-S TPH` (3 strokes). I'm inclined to err on the side of keeping these entries, similar to [these entries](https://github.com/didoesdigital/steno-dictionaries/issues/591#issuecomment-2323099548) and [these entries](https://github.com/didoesdigital/steno-dictionaries/issues/590#issuecomment-2323101725).

`"HR-Z": "{^s will}",` seems to roughly follow the pattern above, assuming `HR` is a brief for "will" and `-Z` is a suffix for `^s`. The main difference between it and the others is that the others prefer `-S` for `^s`, but `HR-S` is already used as `"HR-S": "also",` — overall, I think it's worth keeping. To write "wills", we can still use `"WEULS": "wills"`.

`"SKP-PBS": "{^s and}",` also follows the main pattern but is a little less obvious as it has an extra `-PB` in it, which is used in the phonetic outline for `"ABD": "and",` instead of the brief version `"SKP": "and",`. Following the main pattern, I would expect `^s and` to be stroked using `SKP-S` but that outline is occupied: `"SKP-S": "and is",`, which is similar to its own set like `"SKP-R": "and are",` and `"SKP-T": "and the",` — overall, I think it's worth keeping.

`"TPH/-S": "{^s in}",` looks like a stacking misstroke of `"TPH-S": "{^s in}",` and is no shorter/easier than writing `-S/TPH`, which follows steno order. I'll move that one to `bad-habits.json`

It would be faster to write `KREUBG/ET WHOS/SR` (4 strokes) than `KREUBG/ET/-S WHO SR` (5 strokes), so I'm inclined to keep `"WHOS/SR": "{^s who have}",` which also kind of follows the main pattern, except that 

`"KWR-S": "{^s ,}",` looks like a misstroke. Even if it were following the briefing pattern of swapping strokes to fold in a late steno order suffix and using an outline like `"KW-BG": "{,}",` for the comma, I would expect the translation to be `"{^s, }"` with the comma attached to the "s" and the outline to be `"KW-BGS"`. I'll move this one to bad habits.

The following three entries kind of follow the pattern but place the "A" for the start of the "a-" words at the start, which is a bit of a stretch of the pattern:
```
"AS/HROU": "{^s allow}",
"AS/KWAOEUR": "{^s acquire}",
"AS/RAOEUF": "{^s arrive}",
```
- `^s allow` could be written using `"-S": "{^s}"` and the brief outline `HROU` as `-S HROU` in 2 strokes, the same as `AS/HROU`, so it doesn't add any value.
- `^s arrive` could be written using `"-S": "{^s}"` and the phonetic outline `A/RAOEUF` as `-S A/RAOEUF` in 3 strokes, which is longer than `AS/RAOEUF`, so it *does* add value.
- `^s acquire` could be written using `"-S": "{^s}"` and the phonetic outline `"A/KWAOEUR": "acquire",` as `-S A/KWAOEUR` in 3 strokes, which is longer than `AS/KWAOEUR`, so it *does* add value. To consider the trade-offs of keeping or deleting this entry:
    - If I wanted to write "sat down as choir practice began" using `"AS": "as",` and `"KWAOEUR": "choir",` then `"AS/KWAOEUR": "{^s acquire}",` would cause me to write "sat downs acquire practice began", so this could cause misstrokes.
    - If I wanted to write "when donkeys acquire":
        - Using `"TOPB/KEU": "donkey"` and `"AS/KWAOEUR": "{^s acquire}",` gives me `TOPB/KEU AS/KWAOEUR` "donkeys acquire" in 4 strokes vs `TOPB/KEU/-S A/KWAOEUR` in 5 strokes
        - If we deleted `"AS/KWAOEUR": "{^s acquire}",` then we'd get "donkey as choir"
- There are upsides and downsides to either keeping or deleting these entries. On the balance, I think I'd prefer to keep them present as they are in Plover's `main.json` for now.

Does that all make sense? Seem reasonable?

**Comment by didoesdigital** [comment]
I've published the changes to Typey Type:
- https://didoesdigital.com/typey-type/lookup?q=%5Es%20in (no `TPH/-S`)
- https://didoesdigital.com/typey-type/lookup?q=%5Es%20%2C (no results)

If that all looks good, we can close the issue.

**Comment by Monniasza** [comment]
`"TOPB/KEU": "donkey"` looks like a misstroke. `TKOPB/KEU` looks better, because it adds the missing `K` for the `d` sound.

**Comment by didoesdigital** [comment]
Oops, I meant `"TKOPB/KEU": "donkey",`. `"TOPB/KEU": "donkey",` is already a misstroke in `misstrokes.json` (I'll add it to `bad-habits.json` too.)
