### ISSUE TITLE
A bunch of strokes with stacked `-D` "-ed"

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#590]
# Dictionary

I noticed these dictionary entries in:
- `dict.json`

They were found with `grep "{^ed " dict.json`

# Misstroked entry or entries
These look like misstrokes:
```json
"SAEUPL/-D/TE": "{^ed at the same}",
"T-D": "{^ed it}",
"THAD": "{^ed that}",
"TOD": "{^ed to}",
"TOTD": "{^ed to}",
"TPH-D": "{^ed in}",
"W-D": "{^ed with}",

```

These look like misstrokes because:
- All strokes except `SAEUPL/-D/TE` are the suffix "s" stacked with a word
- `SAEUPL/-D/TE` would be "samed at the" without that entry in the dict.json, which is nonsensical.

# Expected
I would expect the outline to be:
```json
"TE/SAEUPL": "at the same"
```

I would expect to see that outline because:
- It uses a brief `TE` for "at the" and `SAEUPL` for "same"
- It is consistent with the `main.json` dictionary from Plover 3.

# Even better
To make this even better, we could:
- Remove entries completely because they can already be stroked without their own entries. They're not common phrases so they do not need to appear in dictionary look up searches.

**Comment by didoesdigital** [comment]
Thanks @Monniasza!

The issues with `"SAEUPL/-D/TE": "{^ed at the same}",` make sense to me, so I'll remove that.

`"TOTD": "{^ed to}",` looks like a misstroke of `"TOD": "{^ed to}",` with an excess `-T` key included, so I'll remove `"TOTD": "{^ed to}",`

The rest mostly look ok to me. It seems like they are using a rare Plover briefing pattern of both folding a suffix stroke into a word and flipping the steno order of them. For example, `T-D` lets someone write "melted it" using `PHELT T-D` (2 strokes) instead of `PHELT/-D T` (3 strokes). I'm inclined to err on the side of keeping these entries, similar to [these entries](https://github.com/didoesdigital/steno-dictionaries/issues/591#issuecomment-2323099548)

**Comment by didoesdigital** [comment]
I've published the changes to Typey Type:
- https://didoesdigital.com/typey-type/lookup?q=%5Eed%20at%20the%20same (no results)
- https://didoesdigital.com/typey-type/lookup?q=%5Eed%20to (only `TOD`)

If that's all good, let's close this.

**Comment by Monniasza** [comment]
"melted it" can be written as `PHELTD T`.

**Comment by didoesdigital** [comment]
I would probably also use `PHELTD T` over `PHELT T-D` 👍
