### ISSUE TITLE
`merge` misstroke

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#595]
# Dictionary

I noticed this dictionary entry:
- `dict.json`

# Misstroked entry
This looks like a misstroke or could otherwise be better:
```json
"TPHERPBLG": "merge"
```

This looks like a misstroke because:
- `TPHERPBLG` has extra `T`, which sounds like 'nerge'

# Expected
I would expect the outline to be:
```json
"PHERPBLG": "merge",
"TPHERPBLG": "energy"
```

I would expect to see that outline because:
- It is consistent with the `main.json` dictionary from Plover 3.
- `TPHERPBLG` is a potential brief, dropping the 'e' prefix and the 'y' suffix.

**Comment by didoesdigital** [comment]
As shown in the commits linked above, I've removed `"TPHERPBLG": "merge"` as a misstroke with an extra T key.

I've also added `"TPHERPBLG": "energy"` as a brief to `di-briefs.json` as it is very similar to the existing spinal brief `"TPH-RPBLG": "energy"`, just adding the E vowel key. I've added it to `di-briefs.json` instead of `briefs.json` because it diverges from Plover's `main.json`.

Thanks @Monniasza !
