### ISSUE TITLE
`action` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#596]
# Dictionary
I noticed these dictionary entries in:
- `dict.json`

# Misstroked entry or entries
These look like misstrokes or could otherwise be better:
```json
"*BGS": "action",
"*PBGS": "action"
```

This looks like a misstroke because:
- `*BGS` misses the `A`, thus it would be "beings".
- `*PBGS` also adds extra `-P`

# Expected
I would expect the outline to be:
```json
"A*BGS": "action"
```

I would expect to see that outline because:
- It uses `A` for "a" and `*BGS` for "-ction"

# Even better
To make this even better, we could:
- Remove entries completely because they can already be stroked without their own entries.

**Comment by didoesdigital** [comment]
Thanks @Monniasza !

I've removed `"*PBGS": "action"` because it's a misstroke with an extra `P` key. 

`*BGS` could arguably be a brief or misstroke, so I've updated the `top-10000-project-gutenberg-words.json` dictionary to use `A*BGS` as the canonical outline for "action". This is the entry that will show up in [Typey Type Lookup](https://didoesdigital.com/typey-type/lookup?q=action) and stroke hints during lessons. I've also moved `"*BGS": "action",` from `dict.json` to `briefs.json`.

Here are some other related entries for consideration:

```
"-BGSZ": "actions",
"A*BGS/-BL": "actionable",
"A*BGS/TPH/REPL": "action in rem",
"EUPB/*BGS": "inaction",
"RE/-BGS": "reaction",
```

And for anyone else's reference, according to [Art of Chording](https://www.artofchording.com/compounds/shun.html), `BGS` for "kshun" sounds "conflicts with right-side X, which is the exact same chord. Usually, the theory will prefer right-side X, and add an asterisk to give you the kshun ending":

```
TPABGS: fax
TPA*BGS: faction
ABGS: axe
A*BGS: action
```

**Comment by Monniasza** [comment]
`"-BGSZ": "actions"` looks like a double elision. It could be derived `A*BGSZ` => `*BGSZ` => `-BGSZ`.
`"A*BGS/-BL": "actionable"` and `"A*BGS/TPH/REPL": "action in rem"` look alright.
Also, `"RE/-BGS": "reaction"` looks like a misstroke, since `-BGS` is classified as a misstoke of the period.
