### ISSUE TITLE
`it's` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#597]
# Dictionary

I noticed these dictionary entries in:
- `dict.json`

# Misstroked entry or entries
These look like misstrokes or could otherwise be better:
```json
"T-TS": "it's",
"EUTS/AE": "it's"
```

These look like misstrokes because:
- `T-TS` has extra `-T`
- `EUTS/AE` would otherwise be "its'", which is incorrect

# Expected
I would expect the outline to be:
```json
"T-S": "it's"
```

I would expect to see that outline because:
- It uses `T` for "it" and `-S` for "'s"

# Even better
To make this even better, we could:
- Remove the entries completely because they can already be stroked without their own entry.

**Comment by didoesdigital** [comment]
Thanks @Monniasza !

I've removed `"T-S": "it's"` as a misstroke with an extra T key in [this commit](https://github.com/didoesdigital/steno-dictionaries/commit/f2eafb2ef51e8269a6a9d6c387eda4879e85e859). 

I'm ok with leaving `"EUTS/AE": "it's"` because the main entry is `"EUTS": "its",` and `/AE` is sometimes used to retrospectively insert an apostrophe somewhere in the word. Here are some examples:

```
"EUD": "id",
"EUD/AE": "I'd",
"EUL": "ill",
"EUL/AE": "I'll",
"KORTS": "courts",
"KORTS/AE": "court's",
"KPHOPB": "common",
"KPHOPB/AE": "c'mon",
```
