### ISSUE TITLE
The stroke for `important` sounds like  `porn`

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#603]
Hi. I've found that `PORPB` is a stroke for "important". This is surprising since I would expect "porn" to come up as I know the Plover theory. The actual stroke for "porn" is `PAURPB`, which uses the 'aw' sound for the O. Also, `PORPB` misses the `-T` for both Ts in "important".
Please reassign `PORPB` to "porn" and remove `PAURPB`.
The expected stroke is `PORPBT`, which is already defined.

**Comment by didoesdigital** [comment]
As far as I'm aware `PORPB` is widely considered the canonical [brief for "important"](https://www.artofchording.com/sounds/oh.html#briefs). If I recall correctly it specifically intentionally occupies the phonetic outline space that "porn" should, so that it is easier to write the more commonly used word "important" than the less commonly used and possibly Not Safe For Work word "porn".

**Comment by didoesdigital** [comment]
Thanks for raising this and giving visibility to it @Monniasza
