### ISSUE TITLE
`recognize` misstrokes

### ISSUE THREAD

**Issue by Monniasza** [didoesdigital/steno-dictionaries#606]
# Dictionary
I noticed these dictionary entries in:
- `dict.json`

# Misstroked entry or entries
This looks like a misstroke or could otherwise be better:

```json
"REBG/PHAOEUZ": "recognize",
"REBG/TPHAOEUS": "recognize",
"RERBG/TPHAOEUS": "recognize",
"REBG/TPHAOEUDZ": "recognize"
"RAOEBLG/TPHAOEUS": "recognize"
```

This looks like a misstroke because:
- `REBG/PHAOEUZ` misses the `T` on the second stroke
- `REBG/TPHAOEUS`, `RERBG/TPHAOEUS`, and `RAOEBLG"TPHAOEUS` use `-S` instead of `-Z`
- `RERBG/TPHAOEUS` has extra `-R` on the first stroke
- `REBG/TPHAOEUDZ` has extra `-D` on the second stroke, so it sounds like "recognized"
- `RAOEBLG/TPHAOEUS` has `AOE` instead of `E` and also extra `-L`

# Expected
I would expect the outline to be:
```json
"REZ": "recognize"
```

I would expect to see that outline because:
- It is a brief

# Even better
To make this even better, we could:
- Remove entries completely because they can already be stroked without their own entries.

**Comment by didoesdigital** [comment]
Thanks @Monniasza ! Agreed, these can be removed.

The only one I'm not confident about changing is `REBG/TPHAOEUS`, `RERBG/TPHAOEUS`, and `RAOEBLG/TPHAOEUS` only on the basis that they use `-S` instead of `-Z`. Two reasons I'm reluctant: 1. Because in Australian English (or UK or international English), we would use "recognise" anyway. And 2. There are a fair few other instances in the dictionary that allow either an `-S` or `-Z` ending for "-ize" endings, kind of like autocorrect so you don't have to think as hard about which one to use (because either is fine). Some examples:

```
"TKE/SEPBS/TAOEUS": "desensitize",
"TKE/SEPBS/TAOEUZ": "desensitize",
"STRAT/SKWRAOEUS": "strategize",
"STRAT/SKWRAOEUZ": "strategize",
"SAUBS/TKAOEUS": "subsidize",
"SAUBS/TKAOEUZ": "subsidize",
"*EPL/THAOEUS": "empathize",
"*EPL/THAOEUZ": "empathize",
```

I think on the balance I'm inclined to keep those. I don't think they are likely to have a huge impact on misleading beginners. I'll update the other entries when I get a moment.

**Comment by Monniasza** [comment]
`RERBG/TPHAOEUS`, and `RAOEBLG/TPHAOEUS` still have different mistakes.
- `RERBG/TPHAOEUS` also has extra `-R` on the first stroke
- `RAOEBLG/TPHAOEUS` also has `AOE` instead of `E` and also extra `-L`
- But `REBG/TPHAOEUS` has only `-S` instead of `-Z`.

**Comment by didoesdigital** [comment]
Oh right, I totally missed that the third and fourth bullets in your original post repeated outlines from the second bullet, thanks for reiterating the details!

<img width="584" alt="Bullet 1: REBG/PHAOEUZ misses the T on the second stroke. Bullet 2: REBG/TPHAOEUS, RERBG/TPHAOEUS, and RAOEBLG"TPHAOEUS use -S instead of -Z. Bullet 3: RERBG/TPHAOEUS has extra -R on the first stroke. Bullet 4: REBG/TPHAOEUDZ has extra -D on the second stroke, so it sounds like "recognized". Bullet 5: RAOEBLG/TPHAOEUS has AOE instead of E and also extra -L" src="https://github.com/user-attachments/assets/9485e82e-3e88-4a6d-8b3c-c7b0a7208b6f">

I've also noted these Aussie equivalents as misstrokes:

```
"RAOEBLG/TPHAOEUS/A*U": "recognise",
"REBG/PHAOEUZ/A*U": "recognise",
"REBG/TPHAOEUDZ/A*U": "recognise",
"RERBG/TPHAOEUS/A*U": "recognise",
```

The changes are now live! Thanks @Monniasza !
