### ISSUE TITLE
Dictionary entries for "er"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#7]
Currently, the dictionaries have the following entries for "er" (a word which appears in Typey Type exercises, I'm assuming, meaning 'er...', the exclamation expressing hesitation):

`dictionaries/dict.json`
Line 16029: `"ER": "{er^}"`

https://github.com/didoesdigital/steno-dictionaries/blob/5eaf4f5fb55e422c00aad2df8f34d5a9552dca0a/dictionaries/top-1000-words.json#L368

https://github.com/didoesdigital/steno-dictionaries/blob/5eaf4f5fb55e422c00aad2df8f34d5a9552dca0a/dictionaries/top-10000-english-words.json#L4127

https://github.com/didoesdigital/steno-dictionaries/blob/5eaf4f5fb55e422c00aad2df8f34d5a9552dca0a/dictionaries/top-10000-project-gutenberg-words.json#L368

In the Plover dictionary for release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), the keystroke `ER/SP-S` outputs "er ands" or "erands", and the entries for "er" are listed as:

```json
"ER": "{er^}"
"*ER": "{^er}"
```

Stroking just `ER` provides the "er" that would be needed for the Typey-Type exercises, so if I was to make a pull request, I think I would potentially:

- Change all `ER/SP-S` entries above to be just `ER` (or potentially remove the `ER/SP-S` "er" entries altogether if "er" here was not meant to mean the word "er", but rather the prefix or suffix)
- Add the `*ER` entry to `dict.json`

But, I'm not entirely sure, hence this issue. What would be the best changes to make for these dictionary entries?

**Comment by didoesdigital** [comment]
@paulfioravanti, thanks for opening this issue. 

It looks to me like `"ER/SP-S": "er"` was an erroneous attempt to follow Plover dictionary's pattern for forcing spaces in single-letter words like `"*E/SP-S": "e"` and `"R*/SP-S": "r"`. They can be useful for writing a single letter as a word by itself without "glueing" to previous letters like `"*EP": "{&E}"` would. As you point out though, it doesn't work for words like "er" using the standard Plover dictionary so something will need to change.

It would be nice to create briefs for all the words that don't have entries in the Plover dictionary, which I have done in the past, but it would be even better for people to use Typey Type without being forced to use its dictionaries. I think that rules out adding new entries for  outlines like `"ER/SP-S"`.

If we changed all the `"ER/SP-S"` entries to `ER` to use the prefix entry, `"ER": "{er^}"`, or suffix stroke `"*ER": "{^er}"` that might cause word boundary errors for people on the next word or when writing the word "er" without a leading space.

**I suggest we change all the `"ER/SP-S": "er",` entries to `"ER/S-P": "er",`**, combining the prefix entry `"ER": "{er^}"` with the stroke for a space: `"S-P": "{^ ^}"`. This will be consistent with the Plover dictionary and encourage correct spacing to avoid word boundary errors. We can also add that to the "condensed-strokes.json` dictionary because "er" wouldn't actually require its own dictionary entry to write it that way, it would just improve stroke hints and searching.

That sound right, @paulfioravanti?

**Comment by paulfioravanti** [comment]
> I suggest we change all the "ER/SP-S": "er", entries to "ER/S-P": "er",, combining the prefix entry "ER": "{er^}" with the stroke for a space: "S-P": "{^ ^}".

In principle, I agree with this, however, the issue I have had when doing the "er" stroke on Typey Type is that upon stroking just `ER` (without the second stroke), you immediately have a match for the desired "er" output, and you get automatically transitioned to the next word.

This was the confusion that led me to submit this issue, and would probably continue to confuse beginners: ie "why is this showing as a two-stroke word when just one stroke gets me what I need?". If the next word ends up then creating a boundary error, then there is extra confusion since by then you've forgotten the second `S-P` stroke from the previous "er" entry, and are wondering if there's an issue with the displayed stroke for the current word. 

Should Typey Type prevent transition away from the "er" entry until both chords are stroked? Is this even possible, or is it dependent on Plover? The potential complexity of that issue was what made me suggest removing the "er" word entry entirely from Typey Type as a word, since the current Plover dictionary only sees it in prefix and suffix form anyway.

I'm still not sure what the right way forward is for this situation, or for any other keystroke entries that may require some punctuation at the end of the word that a user potentially won't have the opportunity to input.

**Comment by didoesdigital** [comment]
@paulfioravanti I see what you mean. Even swapping it around to `S-P/*ER`, which might help that case, might cause other problems (e.g. if you use the “space after” setting). I don't think Typey Type will be able to prevent transition away from the “er” entry until both chords are stroked, that's dependent on Plover. For entries ending in punctuation, Typey Type keeps the punctuation at the end of the material so it shouldn't transition until you've typed the matching punctuation.

I wonder if the safest path is to **suggest fingerspelling strokes**. I'm reluctant to remove the word “er” as it *is* a word and would ruin the “top X words” word counts 🙂Fingerspelling short words is good practice as well. What do you think?

**Comment by paulfioravanti** [comment]
Fingerspelling those strokes sounds like a great solution to me!

So, if `"ER/SP-S": "er"` should become `"*E/R*": "er"`, then for entries like `"KWR*/*E/SP-S": "ye"`, where it is already being finger-spelled, can the final `SP-S` just be dropped so it becomes `"KWR*/*E": "ye"`? If so, I'll keep that in mind in the future should I find similar entries.

**Comment by didoesdigital** [comment]
That seems like a good approach. Want to open a PR for 'er' and 'ye'?

**Comment by paulfioravanti** [comment]
Yep, happy to. I've just had another look at entries that potentially have an un-strokeable-in-Typey-Type `SP-S` and there is quite a lot in `condensed-strokes.json`, `top-10000-project-gutenberg-words.json`,`top-10000-english-words.json`, and `dict.json`. I'll go through them and submit as a separate PR to the fixes to 'er' and 'ye'. If there are any dictionaries in that list above whose entries you think can be left as-is, I'm happy to leave them out.
