### ISSUE TITLE
Question about stroke for "brings"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#72]
The stroke for "brings" in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), and in the repo dictionaries, is:

```json
"PWREUS": "brings"
```

Although a much longer stroke, I would have expected to see:

```json
"PWREUPBGS": "brings"
```

with the full `PBG` for the "ng" sound in "brings". `PWREUPBGS` does actually work as a stroke for "brings" in Plover, but looks like it's not "officially"(?) recorded as an entry in Plover.

I'm assuming that there's something in steno theory that I'm missing, so I'm not doubting the correctness of the dictionary entry here. But, if, by chance, this is an oversight, is this stroke worth perhaps adding to the Typey-Type dictionaries, even if in an "unofficial" capacity? Or, is this a question perhaps for one of the Plover repos? Or, am I just barking up the wrong tree?

**Comment by didoesdigital** [comment]
I would guess `"PWREUPBGS": "brings"` works because `"PWREUPBG": "bring",` exists as a phonetic entry and `-S` is the suffix `^s` so when you "tuck" or "fold" the `S` in `"PWREUPBGS"`, Plover will automatically handle it through its [orthography rules](https://github.com/openstenoproject/plover/blob/685bd3373dcf19817f59070274a33457ff145701/plover/orthography.py) using the [suffix keys ('-Z', '-D', '-S', '-G') listed in the English stenotype file](https://github.com/openstenoproject/plover/blob/685bd3373dcf19817f59070274a33457ff145701/plover/system/english_stenotype.py#L13).

`"PWREU": "bring"` and `"PWREUS": "brings"` look like briefs to me. One way to see if a brief is intentional (and not a misstroke) is to check for other entries that use it as part of a phrase. In this case, I can see `"PWREU/-G/PABG/SOPL": "bringing back some",` and `"AUP/PWREU/-G": "upbringing",` that also use `PWREU` for "bring".

I would suggest adding `"PWREUPBGS": "brings"` to the `condensed-strokes.json` dictionary to show up in lookups.

As `PWREU` looks like a brief, I would be reluctant to remove `PWREUS` from the `dict.json`, which means Typey Type will continue to recommend it as it's shorter than `PWREUPBGS` and neither have asterisks, multiple strokes or prefixes/suffixes to influence the ranking.

**Comment by paulfioravanti** [comment]
Thanks for the detailed answer, Di!

> One way to see if a brief is intentional (and not a misstroke) is to check for other entries that use it as part of a phrase

Good idea. I'll make sure to do this in the future.

> I would suggest adding "PWREUPBGS": "brings" to the condensed-strokes.json dictionary to show up in lookups.

Sounds good. I'll put in a PR for this.
