### ISSUE TITLE
Issue with stroke for "groups"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#75]
The strokes for "groups" in Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), and in the repo dictionaries, are:

```json
TKPRAOUPS
TPWRAOUPS
TKPWRAOUPS
TKPWRAOUPLS
```

However, in this repo, `TPWRAOUPS` is marked as a mis-stroke:

https://github.com/didoesdigital/steno-dictionaries/blob/69fc1df69bbb32155535444ec64bfbcc7510f01f/dictionaries/misstrokes.json#L2786

This makes sense to me, as it's missing the `K` to make up the full `TKPW` stroke for "g". Given that, I would also like to propose that:

- `TKPRAOUPS` also be moved from `dict.json` to `misstrokes.json`, since it's missing the `W` in `TKPW` for "g"
- The entry for "groups" in `top-10000-project-gutenberg-words.json` 
  https://github.com/didoesdigital/steno-dictionaries/blob/69fc1df69bbb32155535444ec64bfbcc7510f01f/dictionaries/top-10000-project-gutenberg-words.json#L3225
  changed to `TKPWRAOUPS`

**Comment by didoesdigital** [comment]
Great catch @paulfioravanti . I went ahead and made that change. Instead of directly moving it to `misstrokes.json`, which is an automated dictionary created from entries deleted out of `dict.json` that haven't been moved to other dictionaries, I moved it to `bad-habits.json` and ran the script (not open source at this time) to collect misstrokes and update `misstrokes.json`.

To make it easier to find previous decisions about misstrokes, I also added some previously deleted misstrokes for words starting with "g" using `TPW` to `bad-habits.json` that were deleted from `dict.json` but not added to `bad-habits.json`.

I find it convenient to search the history of my dictionary decisions using git like this: `git log -S'"TPWRAOUPS": "groups",' -- dictionaries/dict.json --follow-parent`.
