### ISSUE TITLE
Issue with stroke for "exclusion"

### ISSUE THREAD

**Issue by paulfioravanti** [didoesdigital/steno-dictionaries#90]
In Plover release [weekly-v4.0.0.dev8+66.g685bd33](https://github.com/openstenoproject/plover/releases/tag/weekly-v4.0.0.dev8%2B66.g685bd33), there is no entry for the stroke `KPHRAOUGS` to mean "exclusion", yet it is included in `briefs.json` and `top-10000-project-gutenberg-words.json`.

Rather, the only single stroke entry for "exclusion" in Plover is `SKHRAOUGS`. Also, the two-stroke entry `EBGS/KPHRAOUGS` for "exclusion" is apparently considered valid in Plover, but that entry is currently in `misstrokes.json`. Furthermore, there is a stroke `SKHRAO*UGS` for "exclusion" in `dict.json` that does not seem to be in Plover.

So, my questions are:

- Should `KPHRAOUGS` be moved to `bad-habits.json` and the `KPHRAOUGS` entries in `briefs.json` and `top-10000-project-gutenberg-words.json` be replaced with `SKHRAOUGS`?
- Should `EBGS/KPHRAOUGS` be removed from of `misstrokes.json` and added (back?) into `dict.json`?
- Should `SKHRAO*UGS` be removed from `dict.json` and added to `bad-habits.json`?

**Comment by didoesdigital** [comment]
Thanks for this @paulfioravanti. What a mess!

The main words we want to make sure work nicely together are "exclude"/"exclusion", "include"/"inclusion", "seclude"/"seclusion", and "excuse". 

I believe the challenge is that Plover has `"SKHRAOUD": "exclude",` and `"SKHRAOUD/-D": "secluded",`. If you learn `SKHRAOUD` for exclude, you might reasonably expect `SKHRAOUD/-D` to be "excluded". Plover's dictionary should probably update that entry to `"SKHRAOUD/-D": "excluded",` and that would solve most of the problems.

Looking at the Plover dictionary, it looks like there's good precedent for "exclu-" words claiming the `SKHRAOU` brief space, "inclu-" words claiming the "KHRU" space, and "seclu" words being written out with long form.

"excuse" words might be `KP` or `SK` based e.g.

- `"KPAOUS": "excuse",`
- `"KPAOUFD": "excused",`
- `"KPUPL": "excuse me",`
- `"SKAOUS": "excuse",`
- `"SKAOUS/PHAE": "excuse me",`
- `"EUPB/SKAOUS/-BL": "inexcusable",`

# Fixes

Our current best path forward might be…

… `dict.json` entries for:

```
"SKHRAOUD": "exclude",
"SKHRAO*UD/-D": "excluded",
"SKHRAOUGS": "exclusion",
"SKHRAOUS/EUF": "exclusive",
"SKHRAOUFL": "exclusively",
```

`condensed-strokes.json` entries that use suffix folding for:

```
"SKHRAOUDZ": "excludes",
"SKHRAOUGSZ": "exclusions",
"SKHRAOUD/-S": "excludes",
"SKHRAOUGS/-S": "exclusions",
```

`condensed-strokes.json` entries that would only work with orthography rules for:

```
"SKHRAOUD/-G": "excluding",
"SKHRAOUD/-BL": "excludable",
```

… `bad-habit.json` entries/commits for:

```
"SKAOUS/EUF": "exclusive",
"SKAOUS/EUFL": "exclusively",
```

… because `SKAOUS` is "excuse", making these misstrokes missing the `HR`, and

… a `bad-habit.json` entry/commit for:

```
"SKHRAOUD/-D": "secluded",
```

… because `SKHRAOUD` is "exclude"` and `SE/KHRAOUD` is "seclude", making this an incorrect entry, and

… a `bad-habit.json` entry/commit for:

```
"EBGS/KPHRAOUGS": "exclusion",
```

… because it's using a `KP` for an "x" sound, which is redundant with `EBGS`, where it should be `EBGS/KHR` without a `P` for "ex-" and "clu-" sounds.

… and, optionally, a personal dictionary entry for `"SKHRAOUD/-D": "excluded",` until/if Plover gets that sorted.

**Comment by didoesdigital** [comment]
@paulfioravanti I'm happy to make those changes myself if you agree, so no need to send through a PR.

**Comment by paulfioravanti** [comment]
@didoesdigital Thanks for the detailed explanations, Di! Definitely happy for you to make those changes!

**Comment by didoesdigital** [comment]
I'm fairly confident these recent commits cover everything
